server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL2}
    username: ${DB_USERNAME2}
    password: ${DB_PASSWORD2}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  sql:
    init:
      mode: never

logging:
  level:
    root: info
    org.hibernate.SQL: warn

jwt:
  secret: ${JWT_SECRET2}
  access-token-expiration: 1800000

cors:
  allowed-origins:
    -

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    s3:
      bucket: ${AWS_S3_BUCKET}
