server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL2}
    username: ${DB_USERNAME2}
    password: ${DB_PASSWORD2}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

  sql:
    init:
      mode: never

logging:
  level:
    root: info
    org.hibernate.SQL: warn

app:
  frontend-url: https://hackathon-staycare.netlify.app


openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-5.5

jwt:
  secret: ${JWT_SECRET2}
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000

cors:
  allowed-origins:
    -
firebase:
  service-account-b64: ${FIREBASE_SERVICE_ACCOUNT_B64:}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    s3:
      bucket: ${AWS_S3_BUCKET}

weather:
  openweather:
    api-key: ${OPENWEATHER_API_KEY}
    base-url: https://api.openweathermap.org
    lat: 37.5665
    lon: 126.9780


google:
  calendar:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: https://api.staycare.shop/api/google-calendar/callback
    auth-uri: https://accounts.google.com/o/oauth2/v2/auth
    token-uri: https://oauth2.googleapis.com/token
    scope: https://www.googleapis.com/auth/calendar